### ISSUE TITLE
你好在cocos商店购买了插件，但是工具使用的文档链接无效了

### ISSUE THREAD

**Issue by huahuacn** [antwand/skynet-sproto-js#1]
如题，请问工具应该如何使用？

**Comment by antwand** [comment]
下载下来有说明
----- 原始邮件 -----
发件人：mikewu <notifications@github.com>
收件人：antwand/skynet-sproto-js <skynet-sproto-js@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[antwand/skynet-sproto-js]_你好在cocos商店购买了插件，但是工具使用的文档链接无效了_(#1)
日期：2018年04月20日 00点46分

如题，请问工具应该如何使用？

&mdash;

**Comment by antwand** [comment]
如果还不会 加我qq  2015591797
----- 原始邮件 -----
发件人：mikewu <notifications@github.com>
收件人：antwand/skynet-sproto-js <skynet-sproto-js@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[antwand/skynet-sproto-js]_你好在cocos商店购买了插件，但是工具使用的文档链接无效了_(#1)
日期：2018年04月20日 00点46分

如题，请问工具应该如何使用？

&mdash;
